### ISSUE TITLE
Add (smaller) cursor in default, make it move only horizontally

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#101]
new smaller cursor: 80x80px
![cursor](https://user-images.githubusercontent.com/27123/47757394-d7ef3b00-dcae-11e8-8b60-4120e3be26d1.png)

**Comment by eranws** [comment]
@mushon 
previous size has radius of 40 (inner) and 50 (outer).
now is 30,35. can tweak here:
https://github.com/mushon/The-Normalizing-Machine/blob/master/src/AppCursor.cpp#L8
