### ISSUE TITLE
Debug sample pairing choice logic

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#105]
We currently get test1 or test2 on almost every session, even if they are not being chosen by the participant. We should make sure the next sample is always different than the previous (unchosen) ones. This is currently a major bug that makes the interaction very confusing as participants are constantly asked to chose between other participants they already voted out.

**Comment by eranws** [comment]
We need to refresh our bootstrap procedure for each installation... Easiest
solution is to remove test1 and test2 from dataset.json
We should add a flag to hide test videos on release, once we added more
than 2 videos.
