### ISSUE TITLE
Solve Kinect freeze bug

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#109]
3 options atm, let's try them one by one:

- Debug current setup (look into [this](https://stackoverflow.com/questions/12515132/kinect-hangs-up-suddenly-after-working-pretty-well-a-few-seconds-how-can-i-fix))
- switch from OpenNI to Kinect for Windows SDK (may require a different video mirror solution)
- Use USB buttons for input instead of Kinect

**Comment by dstavy** [comment]
the stuck overflow is for mac and there is no solution there

**Comment by dstavy** [comment]
this is soved as i move to ms kinect. open new issues

**Comment by mushon** [comment]
Hallelujah!
