### ISSUE TITLE
Define sorting algorithm

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#25]
Started writing it here:

While the first iteration of the TNM project was well received, it was more of a prototype than a full project. The full version of the work, which this application is requesting support for, will employ a sophisticated live sorting algorithm that will instantly sort visual appearance according to an emergent scale of "normalcy". The Prej-Rank algorithm, inspired by Google's Page-Rank algorithm will value the ranking made by those deemed "normal" more than by those discarded as abnormal and will dynamically place the participant in the scale, turning the examiner to an examined. The final output is a dynamic growing scale that will be visualized as a disturbing portrait not only of a local community but also of its cultural image of how should a "normal" person look like and what does it consider a deviation from the norm.

**Comment by mushon** [comment]
Reference: https://bost.ocks.org/mike/algorithms/

**Comment by mushon** [comment]
- pick from 2 portraits
- the portrait you chose as "normal" stays and another portrait is added for the next round
- continue until you had enough (?)
- at some point your own portrait is compared with the one you chose (maybe that should be the last round)
- in the background the list of portraits should be sorted
- in idle mode the list should be displayed from most to least normal

**Comment by eranws** [comment]
https://en.wikipedia.org/wiki/Singular_value_decomposition

https://en.wikipedia.org/wiki/Principal_component_analysis

**Comment by mushon** [comment]
linear scale reference:
![uploads/dfb3e70f-58ec-4f47-b84c-5e0ab8e44c38/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdfb3e70f-58ec-4f47-b84c-5e0ab8e44c38%2Fblob)

**Comment by mushon** [comment]
@eranws use the Kiev json as initial reference:
[dataset.json.zip](https://github.com/mushon/Turing-Normalizing-Machine/files/386008/dataset.json.zip)
