### ISSUE TITLE
Patch TNM1 to two screens

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#59]
![image](https://user-images.githubusercontent.com/27123/46856410-0942bc80-ce0f-11e8-9612-0d64e3bc8fc7.png)

[flowchart](https://realtimeboard.com/app/board/o9J_kzcch6A=/)
[mockup flow](https://www.dropbox.com/sh/fm34x8lujqkzy9j/AAAhwwD-00jJqfCITqZlv43ba?dl=0)

Critical:
- [x] build layout as two screens with the mirror screen in the middle
- [x] turn selection to 1D (left/right) axis
- [ ] update calibration screen accordingly

Non-Critical:
- [x] add round count
- [ ] update prompt design
- [ ] update time-out design
- [ ] show ">" animated mark
- [x] add animations
- [ ] allow non-Kinect control (might be critical for agile development)

**Comment by eranws** [comment]
@mushon 
Layout - last time we used 380x480 (WxH) to fit 768 wide screen (rotated 90 deg), what are we going to use now? is there any specific resolution we're aiming for?
Selection - I think the pointing mechanism (projecting to actual point in the screen) was cumbersome, should we revert to simpler one? the upside is that people are forced to be in very similar pose.

**Comment by mushon** [comment]
This time we use wide HD projections - 1920*1080. So sample loop sizes will be 3*4 proportions (portrait) and appear in default in 513*685px size (though we would prefer capturing them in higher resolution for the face recognition and sampling quality). Note we will be recording the video samples from a secondary webcam, not the Kinect which will provide a higher video resolution.
CCing @dstavy for more context.

**Comment by eranws** [comment]
@mushon - what do you mean by "update calibration screen accordingly"?

**Comment by mushon** [comment]
@eranws since our calibration screen expected a 2D pointing frame and now it's only 1D, calibration should be simpler, but would still require some work.
Additionally, if we can calibrate the projection angle / projection mapping (if that's needed) thing that would be great too.

**Comment by mushon** [comment]
@eranws would you guide me / us how to get:
"allow non-Kinect control (might be critical for agile development)" to work?
