### ISSUE TITLE
Set up 5 selection rounds

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#61]
![image](https://user-images.githubusercontent.com/27123/46856742-f1b80380-ce0f-11e8-94ce-684522710e5e.png)

[flowchart](https://realtimeboard.com/app/board/o9J_kzcch6A=/)
[mockup flow](https://www.dropbox.com/sh/fm34x8lujqkzy9j/AAAhwwD-00jJqfCITqZlv43ba?dl=0)

Critical:
- [x] set up 5 rounds
- [x] document the results of each round in JSON file

Non-Critical:
- [x] last participant is always a part of round 1
- [x] current participant is always a part of round 5 (#60)
- [x] add round count
- [ ] show rounds transition  (see [mockup flow](https://www.dropbox.com/sh/fm34x8lujqkzy9j/AAAhwwD-00jJqfCITqZlv43ba?dl=0))
- [ ] show final winner (see [mockup flow](https://www.dropbox.com/sh/fm34x8lujqkzy9j/AAAhwwD-00jJqfCITqZlv43ba?dl=0))

**Comment by eranws** [comment]
storing sessionId - id of first selection
https://github.com/mushon/The-Normalizing-Machine/blob/master/src/RecordedData.h#L70

we use the same dataset as before, so each id is of a 'selection', in each 'session', there are 5 selections
