### ISSUE TITLE
Define rules for group differentiation per fragment

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#73]

**Comment by mushon** [comment]
@dstavy please review suggested fragmentation and clustering rules.
The solid frames show the slices to use, the dashed lines show the parameters to cluster by.
Please always use the dashed parameter line in reference to the blue dashed line (the standardizing parameter).
![face fragment clustering](https://user-images.githubusercontent.com/27123/46922294-7755d200-d00f-11e8-96d3-2fa4e6c9df4a.png)

**Comment by dstavy** [comment]
we go without the ears for now?
what is the ratio of the extra part of the  head  and forhead?

**Comment by mushon** [comment]
this is only for the front fragments (which I suggest we start with).
I would like us to get a better idea of the fidelity we have on profile and then define these fragments.

**Comment by mushon** [comment]
set groups differentiation by ratio (like eyebrow curve, nose height/width ratio etc…) rather than by comparison with center line

**Comment by mushon** [comment]
### Nose (proportions)
[P34,P38]  / [P32,P36]

### Forehead (Eyebrow curve)
Angle curve: [P23,P25,P27] + [P18,P20,P22]

### Eyes (shape)
Angle curve: [P37,P38,P40] + [P43,P45,P46]

### Mouth (lips proportions)
Lips size in comparison to mouth width:
[[P51,P62]+[P68,P59]+[P53,P64]+[P66,P57]] / [P49,P55]

### Head (proportions)
[P2,P16]  / [P28,P9]

**Comment by mushon** [comment]
@dstavy I would be happy to suggest similar group props for the profile based on examples of the data we get from the camera / detection

**Comment by mushon** [comment]
Side view crops:
![image](https://user-images.githubusercontent.com/27123/47206254-dc535400-d390-11e8-9345-09bf6542b794.png)

**Comment by mushon** [comment]
## Side group parameters

### Nose / side (curve)
Angle curve: [P30,P34,P36]

### Contour (curve)
Angle curve: [P28,P34,P9]

### Chin (curve)
Angle curve: [P34,P9,P12] 

### Side
???

### Ears
???

I would love to get some suggestions for the last two
