### ISSUE TITLE
Install ofxWatchDog and other installation forever plugins

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#78]
https://openframeworks.cc/ofBook/chapters/installation_up_4evr_macosx.html#alternateresources

**Comment by dstavy** [comment]
i am going to do to add ofxwatchdog.

**Comment by mushon** [comment]
@dstavy if this is done, please close.

**Comment by dstavy** [comment]
found a win version 

https://github.com/Akira-Hayasaka/oF_Win_Watchdog.
