### ISSUE TITLE
Store body measurements with video

### ISSUE THREAD

**Issue by eranws** [mushon/The-Normalizing-Machine#80]
Height (head-feet)
Torso length (neck-waist)
Torso width (shoulders)

**Comment by mushon** [comment]
Awesome!
Let’s add them with these variables to the arrest card

**Comment by eranws** [comment]
added in 908ac5c.
I'm taking the max measurement from all frames. (sometimes it can get to 3000mm, so sanity checks are needed)

@dstavy here's an output sample
```
{
      "id" : "2018_10_27_11_42_38_276.oni",
      "others" : [
         {
            "id" : "2018_10_27_11_41_46_374.oni",
            "selection" : true
         },
         {
            "id" : "2018_10_27_11_42_33_418.oni",
            "selection" : false
         }
      ],
      "sessionId" : "2018_10_27_11_42_14_657.oni",
      "shouldersWidth" : 314.4367980957031,
      "torsoLength" : 457.2334899902344,
      "totalHeight" : 1536.057006835938,
      "vScore" : 0,
      "xScore" : 0
   }
```

**Comment by dstavy** [comment]
Height (head-feet) is no good need head alone from the ground
need the neck point as well. one below the head

**Comment by eranws** [comment]
added head Height:
{
      "headHeight" : 237.9399719238281,
      "id" : "2018_10_27_12_56_51_197.oni",
      "others" : [
         {
            "id" : "2018_10_22_00_38_05_397.oni",
            "selection" : false
         },
         {
            "id" : "2018_10_27_11_42_38_276.oni",
            "selection" : true
         }
      ],
      "sessionId" : "2018_10_27_12_56_51_197.oni",
      "shouldersWidth" : 350.9483642578125,
      "torsoLength" : 510.3260498046875,
      "totalHeight" : 1674.494873046875,
      "vScore" : 0,
      "xScore" : 0
   }

**Comment by eranws** [comment]
I made some changes, you should use 'id' field.
Please see recent dataset.json here:
https://github.com/mushon/The-Normalizing-Machine/blob/master/bin/Data/records/dataset.json

**Comment by dstavy** [comment]
found it
