### ISSUE TITLE
Position screen - implement design

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#92]
![prompt_0 2_position](https://user-images.githubusercontent.com/27123/47675898-d432ba00-dbc3-11e8-87a8-d2da4e638a04.png)
![placemark](https://user-images.githubusercontent.com/27123/47675911-da289b00-dbc3-11e8-81ae-c937408464b3.png)
![input-0 2-position](https://user-images.githubusercontent.com/27123/47675961-f62c3c80-dbc3-11e8-9fb7-bfddb5072b61.png)

*red marker is not a high priority

**Comment by eranws** [comment]
What if user is too far/near?
Show up/down arrow? (Currently there's a top down view we can use)

**Comment by mushon** [comment]
We will have a mark on the ground, so this is not a priority. We should support a pretty wide range.
