### ISSUE TITLE
One by One - implement design

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#94]
![prompt_0 3_onebyone](https://user-images.githubusercontent.com/27123/47676163-82d6fa80-dbc4-11e8-8a0e-59169ff28b08.png)

![input-0 3-position-many](https://user-images.githubusercontent.com/27123/47676152-78b4fc00-dbc4-11e8-9b27-535cd02eb1d2.png)

**Comment by eranws** [comment]
@mushon in the new asset, the person on the right has a line sticking into his body
![image](https://user-images.githubusercontent.com/770012/47764011-9c964180-dc99-11e8-8e54-63d9f213b9fe.png)

**Comment by mushon** [comment]
Fixed, thanks!
https://github.com/mushon/The-Normalizing-Machine/commit/49bba22bdf3e293462c6733b40ab18e30a4c4944
