### ISSUE TITLE
Goodbye - implement design

### ISSUE THREAD

**Issue by mushon** [mushon/The-Normalizing-Machine#96]
![prompt_10_goodbye](https://user-images.githubusercontent.com/27123/47676488-6edfc880-dbc5-11e8-9edf-7180b8007136.png)

![input-set10](https://user-images.githubusercontent.com/27123/47676496-73a47c80-dbc5-11e8-8a94-051ffee40b32.png)

**Comment by eranws** [comment]
@mushon please upload assets with the size of 380x480 (three-**EIGHTY** by four-eighty)
